import crypto from "node:crypto";
import esbuild from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const DEBUG_BLOCK_START = "/*  *** DEBUG START ***";
export const DEBUG_BLOCK_END = "//  *** DEBUG END ***/";
const DEBUG_BLOCK_PATTERN = /\/\*\s+\*\*\* DEBUG START \*\*\*[\s\S]*?\/\/\s+\*\*\* DEBUG END \*\*\*\//g;
const NODE_TEST_BANNER = "Remove comments for testing in NODE";

/** @type {readonly string[]} */
export const SOURCE_FILES = Object.freeze([
    "CacheFinance.js",
    "ScriptSettings.js",
    "CacheFinance3rdParty.js",
    "CacheFinanceTest.js",
    "CacheFinanceWebSites.js",
    "CacheFinanceUtils.js"
]);

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const paths = Object.freeze({
    root: rootDir,
    src: path.join(rootDir, "src"),
    dist: path.join(rootDir, "dist", "CacheFinance.js"),
    distMin: path.join(rootDir, "dist", "CacheFinance.min.js")
});

/**
 * Remove Node.js-only DEBUG blocks from Apps Script source files.
 * @param {string} content
 * @returns {string}
 */
export function stripDebugBlocks(content) {
    return content.replace(DEBUG_BLOCK_PATTERN, "").trim();
}

/**
 * Uncomment DEBUG blocks so Vitest can import src modules in Node.
 * @param {string} content
 * @returns {string}
 */
export function enableDebugExports(content) {
    if (!content.includes(DEBUG_BLOCK_START)) {
        return content;
    }

    const startIdx = content.indexOf(DEBUG_BLOCK_START);
    const endIdx = content.indexOf(DEBUG_BLOCK_END, startIdx);
    if (endIdx === -1) {
        return content;
    }

    const before = content.slice(0, startIdx);
    const after = content.slice(endIdx + DEBUG_BLOCK_END.length);
    const debugBody = content.slice(startIdx + DEBUG_BLOCK_START.length, endIdx);

    const uncommented = debugBody
        .split("\n")
        .map((line) => line.replace(/^\/\/\s?/, ""))
        .filter((line) => line.trim() !== NODE_TEST_BANNER)
        .join("\n");

    return `${before}${uncommented}${after}`;
}

/**
 * @param {string[]} sections
 * @returns {string}
 */
export function hashSections(sections) {
    return crypto
        .createHash("sha256")
        .update(sections.join("\0"))
        .digest("hex")
        .slice(0, 12);
}

/**
 * @param {string} sourceHash
 * @returns {string}
 */
export function createBundleBanner(sourceHash) {
    return [
        "/*",
        " * CacheFinance Apps Script bundle.",
        " * Generated from src/. Do not edit this file directly.",
        ` * Source hash: ${sourceHash}`,
        " */",
        ""
    ].join("\n");
}

/**
 * @param {string} sourceHash
 * @returns {string}
 */
export function createMinBundleBanner(sourceHash) {
    return `/* CacheFinance Apps Script bundle (minified). Generated from src/. Source hash: ${sourceHash} */\n`;
}

/**
 * @param {string} bundle
 * @returns {string}
 */
export function minifyBundle(bundle) {
    const { code } = esbuild.transformSync(bundle, {
        minify: true,
        legalComments: "none"
    });

    return code;
}

/**
 * @param {string} content
 */
export function validateBundleContent(content) {
    const errors = [];

    if (!content.includes("function CACHEFINANCE")) {
        errors.push("missing CACHEFINANCE custom function");
    }
    if (!content.includes("function CACHEFINANCES")) {
        errors.push("missing CACHEFINANCES custom function");
    }
    if (content.includes("DEBUG START")) {
        errors.push("contains DEBUG block markers");
    }
    if (content.includes("GasMocks")) {
        errors.push("contains test-only GasMocks references");
    }
    if (content.includes("function testYieldPct")) {
        errors.push("contains optional Apps Script test helpers");
    }
    if (/^[ \t]*import\s/m.test(content) || /^[ \t]*export\s/m.test(content)) {
        errors.push("contains ES module import/export statements");
    }

    if (errors.length > 0) {
        throw new Error(`Invalid bundle: ${errors.join(", ")}`);
    }
}

/**
 * @returns {string[]}
 */
export function readSourceSections() {
    return SOURCE_FILES.map((fileName) => {
        const filePath = path.join(paths.src, fileName);
        if (!fs.existsSync(filePath)) {
            throw new Error(`Missing source file: ${filePath}`);
        }

        return stripDebugBlocks(fs.readFileSync(filePath, "utf8"));
    });
}

/**
 * @returns {{ bundle: string, sourceHash: string, sectionCount: number }}
 */
export function buildCacheFinanceBundle() {
    const sections = readSourceSections();
    const sourceHash = hashSections(sections);
    const bundle = `${createBundleBanner(sourceHash)}${sections.join("\n\n")}\n`;

    validateBundleContent(bundle);

    return {
        bundle,
        sourceHash,
        sectionCount: sections.length
    };
}

/**
 * @param {string} bundle
 * @param {string} sourceHash
 * @returns {string}
 */
export function buildCacheFinanceMinBundle(bundle, sourceHash) {
    const minBundle = `${createMinBundleBanner(sourceHash)}${minifyBundle(bundle)}`;

    validateBundleContent(minBundle);

    return minBundle;
}

/**
 * @returns {{ written: boolean, bundle: string, sourceHash: string, bytes: number }}
 */
/**
 * @param {string} filePath
 * @param {string} content
 * @returns {{ written: boolean, bytes: number }}
 */
function writeBundleFile(filePath, content) {
    const bytes = Buffer.byteLength(content, "utf8");
    const previous = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : null;

    if (previous === content) {
        return { written: false, bytes };
    }

    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content, "utf8");

    return { written: true, bytes };
}

/**
 * @returns {{
 *   written: boolean,
 *   minWritten: boolean,
 *   bundle: string,
 *   minBundle: string,
 *   sourceHash: string,
 *   bytes: number,
 *   minBytes: number,
 *   sectionCount: number
 * }}
 */
export function writeCacheFinanceBundle() {
    const { bundle, sourceHash, sectionCount } = buildCacheFinanceBundle();
    const minBundle = buildCacheFinanceMinBundle(bundle, sourceHash);
    const distResult = writeBundleFile(paths.dist, bundle);
    const minResult = writeBundleFile(paths.distMin, minBundle);

    return {
        written: distResult.written,
        minWritten: minResult.written,
        bundle,
        minBundle,
        sourceHash,
        bytes: distResult.bytes,
        minBytes: minResult.bytes,
        sectionCount
    };
}

/**
 * @returns {boolean}
 */
export function isCacheFinanceBundleCurrent() {
    if (!fs.existsSync(paths.dist) || !fs.existsSync(paths.distMin)) {
        return false;
    }

    const { bundle, sourceHash } = buildCacheFinanceBundle();
    const minBundle = buildCacheFinanceMinBundle(bundle, sourceHash);

    return fs.readFileSync(paths.dist, "utf8") === bundle
        && fs.readFileSync(paths.distMin, "utf8") === minBundle;
}
